# Docker Compose configuration for RTI Dashboard
# To be filled later 

version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - rti-net
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8443:8443"
    networks:
      - rti-net
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rti_dashboard
      SPRING_DATASOURCE_USERNAME: rti_user
      SPRING_DATASOURCE_PASSWORD: rti_pass
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: rti_dashboard
      POSTGRES_USER: rti_user
      POSTGRES_PASSWORD: rti_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rti-net
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    networks:
      - rti-net
networks:
  rti-net:
    driver: bridge
volumes:
  postgres_data: 