spring:
  application:
    name: rti-dashboard-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/rti_dashboard
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  
  flyway:
    enabled: false
  
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
      enabled: true

server:
  port: 8080

app:
  upload:
    max-file-size: 26214400  # 25MB in bytes
    max-rows: 200000
    directory: uploads
  csv:
    preview-row-limit: 100
    max-columns: 50
  dimension:
    time-patterns: "2020,2021,2022,2023,2024,2025,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Q1,Q2,Q3,Q4,January,February,March,April,May,June,July,August,September,October,November,December"
    location-patterns: "USA,Canada,Mexico,UK,Germany,France,Spain,Italy,China,Japan,India,Brazil,Australia,Netherlands,Switzerland,Sweden,Norway,Denmark,Finland,Poland,Czech Republic,Slovakia,Hungary,Romania,Bulgaria,Greece,Portugal,Ireland,Belgium,Austria"
    confidence-threshold: 0.7
    min-sample-size: 5
    max-sample-size: 50

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    io.dashboard: DEBUG 