spring:
  application:
    name: rti-dashboard-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/rti_dashboard
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  
  flyway:
    enabled: false
  
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
      enabled: true

server:
  port: 8080

app:
  upload:
    max-file-size: 26214400  # 25MB in bytes
    max-rows: 200000
    directory: uploads

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    io.dashboard: DEBUG 